### ISSUE TITLE
Keyboard shortcut not working past 0.3.1

### ISSUE THREAD

**Issue by a-c-m** [kitlangton/Hex#124]
**Describe the bug**
When i upgraded to 0.5.3 the hotkey to start recording no longer worked. I tried 0.5.0 also still didn't work. 0.3.1 does however. 

**To Reproduce**
1. Download 0.5.3 or 0.5.0
2. hold alt
3. don't hear the click

**Expected behavior**
It to work

**Screenshots**

**Desktop (please complete the following information):**
- MBP - 16-inch, 2023
- M2 Max
- macOS - 15.7.1 (24G231)

**Additional context**

**Comment by kitlangton** [comment]
Hey! Really sorry about the hotkey issues on Sequoia 15.7.1. I just released version 0.5.4 that should fix this – the problem was that macOS 15 split the old Accessibility permission into separate Accessibility + Input Monitoring permissions, and Hex wasn't properly handling the new Input Monitoring permission.

I don't have a Sequoia machine to test on myself, so I'd really appreciate it if you could try 0.5.4 and let me know if it works! You can download it from https://hex-updates.s3.amazonaws.com/Hex-0.5.4.dmg

If it still doesn't work, please reopen this issue and I'll dig deeper. Thanks for your patience!

**Comment by chasemccoy** [comment]
@kitlangton I am still seeing this issue on 0.5.4 on Sequoia 15.7.2 after updating from 0.3.1

**Comment by kitlangton** [comment]
I actually just pushed 0.5.5 :D Hopefully, hopefully, hopefully this fixes it 🤞 If you get a chance to test it out, let let me know.

**Comment by chasemccoy** [comment]
@kitlangton unfortunately still not working for me... it seems to have permissions and I've successfully set the hotkey to be my function key, but nothing happens when I press the key. I even tried deleting the `com.kitlangton.Hex` folder and re-installing but no luck.

**Comment by kitlangton** [comment]
Thanks for checking. I'll need to figure out a way to install Sequoia somewhere 😭

**Comment by casscors** [comment]
Chiming in here to say that I was working with `0.3.1` and it was great for a day or so, but then app stopped responding at all to any hotkey regardless of reinstall, resetting permissions, etc. The issue still persisted after I tried upgrading to `0.5.5` and resetting permissions.

EDIT: Broken in `0.5.7` too

I then tried updating MacOS to 15.7.2 (24G325) from 15.6.x (not sure).. Issue persisted. Couple of reboots throughout this process to be sure.

Just got it working again by rolling back to `0.3.1`🤷‍♀️ Glad to have it back!

**Comment by vvinhas** [comment]
Having the same issue :( 
I'm also running Sequoia 15.7.2

**Comment by kitlangton** [comment]
<img width="1090" height="316" alt="Image" src="https://github.com/user-attachments/assets/fd7cc58b-6071-4b0f-a9c7-2aa6fde8ec59" />

I just released a version that lets you export logs.

If anyone has a chance to download it and is comfortable sending me their logs, I could see if there are any clues.

**Comment by chasemccoy** [comment]
here ya go @kitlangton hex is showing that all permissions are granted and I have a hotkey set but it doesn't seem to be triggering anything. 

[Hex-Logs-2025-11-18T15:45:29Z.log](https://github.com/user-attachments/files/23609081/Hex-Logs-2025-11-18T15.45.29Z.log)

**Comment by vvinhas** [comment]
> Having the same issue :( I'm also running Sequoia 15.7.2

After reading the messages, I updated to Tahoe 26.1 and it's working fine 🎉

**Comment by chasemccoy** [comment]
@kitlangton No luck with 0.5.12 but here's an updated log file: 

[Hex-Logs-2025-11-18T18:25:50Z.log](https://github.com/user-attachments/files/23611743/Hex-Logs-2025-11-18T18.25.50Z.log)
